import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/provider/auth'
import Footer from '@/components/ui/footer'
import CartProvider from '@/provider/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // envolvi minha aplicação em uma div h-full e coloquei o conteudo entre header e footer para ficar no meio 
  // esse flex-1 ocupa todo o espaço que sobra
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-full'>
          <AuthProvider>
            <CartProvider>
              <Header/>
                <div className="flex-1">
                  {children}
                </div>
              <Footer/>
            </CartProvider>
          </AuthProvider>
        </div>

        </body>
    </html>
  )
}
